apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: balance-api
  namespace: simple-balance
spec:
  releaseName: balance-api
  chart:
    name: balance-api
    version: "0.1.0"
    sourceRef:
      kind: HelmRepository
      name: familymcgee
      namespace: flux-system
  interval: 1m
  install:
    remediation:
      retries: 3

