apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: balance-api
  namespace: simple-balance
spec:
  releaseName: balance-api
  chart:
    repository: https://familymcgee.jfrog.io/fls-docker-repo
    name: balance-api
    version: "0.1.0"
  interval: 5m
  install:
    remediation:
      retries: 3

