apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: balance-api
  namespace: simple-balance
spec:
  chart:
    spec:
      version: ">=0.1.0"
  test:
    enable: false
  values:
    ingress:
      hosts:
        - podinfo.staging
