# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
# namespace: podinfo
# resources:
#   - ../base/podinfo
# patchesStrategicMerge:
#   - podinfo-values.yaml
# ---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: simple-balance
resources:
  - ../base/balance-api  
patchesStrategicMerge:
  - simple-balance-values.yaml